
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.formulariosweb.analizadores.db;

import com.froi.formulariosweb.entidadesfundamentales.*;
import java.util.ArrayList;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserGuardado extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserGuardadoSym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserGuardado() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserGuardado(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserGuardado(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\061\000\002\002\004\000\002\002\006\000\002\002" +
    "\006\000\002\002\006\000\002\003\005\000\002\003\003" +
    "\000\002\004\005\000\002\005\005\000\002\005\003\000" +
    "\002\006\005\000\002\006\005\000\002\006\005\000\002" +
    "\006\005\000\002\006\005\000\002\006\005\000\002\006" +
    "\007\000\002\006\007\000\002\020\005\000\002\020\003" +
    "\000\002\007\005\000\002\007\005\000\002\011\005\000" +
    "\002\011\002\000\002\012\005\000\002\012\005\000\002" +
    "\012\005\000\002\012\005\000\002\012\005\000\002\012" +
    "\005\000\002\012\005\000\002\012\005\000\002\012\005" +
    "\000\002\012\005\000\002\012\005\000\002\012\005\000" +
    "\002\010\005\000\002\013\005\000\002\013\003\000\002" +
    "\014\005\000\002\014\005\000\002\015\005\000\002\015" +
    "\003\000\002\016\005\000\002\016\005\000\002\017\005" +
    "\000\002\017\003\000\002\021\005\000\002\021\005\000" +
    "\002\021\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\201\000\006\006\004\007\005\001\002\000\004\027" +
    "\041\001\002\000\004\027\010\001\002\000\004\002\007" +
    "\001\002\000\004\002\001\001\002\000\006\003\011\004" +
    "\013\001\002\000\004\030\040\001\002\000\006\030\uffd8" +
    "\031\036\001\002\000\012\003\016\010\017\011\022\017" +
    "\020\001\002\000\004\030\015\001\002\000\004\002\uffff" +
    "\001\002\000\004\005\035\001\002\000\004\032\033\001" +
    "\002\000\004\032\031\001\002\000\006\005\uffd4\031\027" +
    "\001\002\000\004\032\025\001\002\000\004\005\024\001" +
    "\002\000\006\030\uffd7\031\uffd7\001\002\000\004\064\026" +
    "\001\002\000\006\005\uffd2\031\uffd2\001\002\000\010\010" +
    "\017\011\022\017\020\001\002\000\004\005\uffd5\001\002" +
    "\000\004\064\032\001\002\000\006\005\uffd1\031\uffd1\001" +
    "\002\000\004\064\034\001\002\000\006\005\uffd3\031\uffd3" +
    "\001\002\000\006\030\uffd6\031\uffd6\001\002\000\004\004" +
    "\013\001\002\000\004\030\uffd9\001\002\000\004\002\ufffe" +
    "\001\002\000\004\004\043\001\002\000\004\030\203\001" +
    "\002\000\022\012\050\013\052\014\057\015\054\016\047" +
    "\017\056\020\053\021\051\001\002\000\006\030\ufffc\031" +
    "\045\001\002\000\004\004\043\001\002\000\004\030\ufffd" +
    "\001\002\000\004\032\201\001\002\000\004\032\177\001" +
    "\002\000\004\032\157\001\002\000\004\032\155\001\002" +
    "\000\004\032\072\001\002\000\004\032\070\001\002\000" +
    "\004\005\067\001\002\000\004\032\065\001\002\000\004" +
    "\032\063\001\002\000\006\005\ufff9\031\061\001\002\000" +
    "\022\012\050\013\052\014\057\015\054\016\047\017\056" +
    "\020\053\021\051\001\002\000\004\005\ufffa\001\002\000" +
    "\004\064\064\001\002\000\006\005\ufff6\031\ufff6\001\002" +
    "\000\004\064\066\001\002\000\006\005\ufff3\031\ufff3\001" +
    "\002\000\006\030\ufffb\031\ufffb\001\002\000\004\064\071" +
    "\001\002\000\006\005\ufff5\031\ufff5\001\002\000\004\027" +
    "\073\001\002\000\004\004\076\001\002\000\004\030\154" +
    "\001\002\000\006\030\uffef\031\152\001\002\000\036\003" +
    "\112\005\uffeb\023\077\024\103\025\110\026\106\033\107" +
    "\034\113\035\104\036\101\037\100\040\105\041\111\065" +
    "\102\001\002\000\004\032\150\001\002\000\004\032\146" +
    "\001\002\000\004\032\144\001\002\000\004\032\142\001" +
    "\002\000\004\032\140\001\002\000\004\032\136\001\002" +
    "\000\004\032\134\001\002\000\004\032\132\001\002\000" +
    "\004\032\130\001\002\000\004\032\126\001\002\000\004" +
    "\032\124\001\002\000\004\005\123\001\002\000\004\032" +
    "\121\001\002\000\004\005\120\001\002\000\004\031\116" +
    "\001\002\000\034\005\uffeb\023\077\024\103\025\110\026" +
    "\106\033\107\034\113\035\104\036\101\037\100\040\105" +
    "\041\111\065\102\001\002\000\004\005\uffec\001\002\000" +
    "\006\030\uffee\031\uffee\001\002\000\004\064\122\001\002" +
    "\000\004\031\uffe4\001\002\000\006\030\uffed\031\uffed\001" +
    "\002\000\004\064\125\001\002\000\004\031\uffdf\001\002" +
    "\000\004\064\127\001\002\000\004\031\uffe7\001\002\000" +
    "\004\064\131\001\002\000\004\031\uffe6\001\002\000\004" +
    "\064\133\001\002\000\004\031\uffe5\001\002\000\004\064" +
    "\135\001\002\000\004\031\uffe0\001\002\000\004\064\137" +
    "\001\002\000\004\031\uffe3\001\002\000\004\064\141\001" +
    "\002\000\004\031\uffe8\001\002\000\004\064\143\001\002" +
    "\000\004\031\uffea\001\002\000\004\064\145\001\002\000" +
    "\004\031\uffe2\001\002\000\004\064\147\001\002\000\004" +
    "\031\uffe1\001\002\000\004\064\151\001\002\000\004\031" +
    "\uffe9\001\002\000\004\004\076\001\002\000\004\030\ufff0" +
    "\001\002\000\006\005\ufff2\031\ufff2\001\002\000\004\064" +
    "\156\001\002\000\006\005\ufff7\031\ufff7\001\002\000\004" +
    "\027\160\001\002\000\004\004\162\001\002\000\004\030" +
    "\176\001\002\000\006\062\164\063\166\001\002\000\004" +
    "\005\175\001\002\000\004\032\173\001\002\000\006\005" +
    "\uffdc\031\171\001\002\000\004\032\167\001\002\000\004" +
    "\064\170\001\002\000\006\005\uffda\031\uffda\001\002\000" +
    "\006\062\164\063\166\001\002\000\004\005\uffdd\001\002" +
    "\000\004\064\174\001\002\000\006\005\uffdb\031\uffdb\001" +
    "\002\000\004\030\uffde\001\002\000\006\005\ufff1\031\ufff1" +
    "\001\002\000\004\064\200\001\002\000\006\005\ufff8\031" +
    "\ufff8\001\002\000\004\064\202\001\002\000\006\005\ufff4" +
    "\031\ufff4\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\201\000\004\002\005\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\015\013\016\011\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\017\022\021\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\017\027\021\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\015\036\016\011" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\003" +
    "\041\004\043\001\001\000\002\001\001\000\006\005\054" +
    "\006\057\001\001\000\002\001\001\000\006\003\045\004" +
    "\043\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\005\061\006" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\007\074\020\073\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\011\113\012\114\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\011\116\012\114\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\007\074\020\152\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\010\160\001\001" +
    "\000\002\001\001\000\006\013\162\014\164\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\013" +
    "\171\014\164\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserGuardado$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserGuardado$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserGuardado$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private ArrayList<Usuario> listaUsuarios;
    private ArrayList<Formulario> listaFormularios;
    private ArrayList<Componente> listaComponentes;
    private String p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11;
    private String c1, c2, c3, c4, c5, c6;
    
    
    public ParserGuardado(GuardadoLexer lexer, ArrayList<Usuario> listaUsuarios, ArrayList<Formulario> listaFormularios) {
        super(lexer);
        this.listaUsuarios = listaUsuarios;
        this.listaFormularios = listaFormularios;
        this.listaComponentes = new ArrayList<>();
    }
    public void report_error(String message, Object info) {
        System.out.println("reporterror");
    }
    public void report_fatal_error(String message, Object info) {
        System.out.println("reportfatal " + info);
    }
    @Override
    public void syntax_error(Symbol s) {
        System.out.println("linea: " + s.left + "   columna: " + s.right);
    }
    protected int error_sync_size() {
        return 1;
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserGuardado$actions {
  private final ParserGuardado parser;

  /** Constructor */
  CUP$ParserGuardado$actions(ParserGuardado parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserGuardado$do_action_part00000000(
    int                        CUP$ParserGuardado$act_num,
    java_cup.runtime.lr_parser CUP$ParserGuardado$parser,
    java.util.Stack            CUP$ParserGuardado$stack,
    int                        CUP$ParserGuardado$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserGuardado$result;

      /* select the action based on the action number */
      switch (CUP$ParserGuardado$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		RESULT = start_val;
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserGuardado$parser.done_parsing();
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= DB_FORMULARIOS PARENT_A instruccion_formulariosdb PARENT_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= DB_USUARIOS PARENT_A instruccion_usuariosdb PARENT_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // inicio ::= DB_USUARIOS PARENT_A error PARENT_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion_formulariosdb ::= valores_formulariosdb COMA instruccion_formulariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_formulariosdb",1, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion_formulariosdb ::= valores_formulariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_formulariosdb",1, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // valores_formulariosdb ::= LLAVE_A acciones_formulariosdb LLAVE_C 
            {
              Object RESULT =null;
		
                                                                                                System.out.println("aún no pasa");
                                                                                                for(Componente element: listaComponentes) {
                                                                                                    System.out.println(element.getClase());
                                                                                                }
                                                                                                System.out.println("ya pasó");
                                                                                                
                                                                                                c1 = (c1.substring(1, c1.length()-1));
                                                                                                c2 = (c2.substring(1, c2.length()-1));
                                                                                                c3 = (c3.substring(1, c3.length()-1));
                                                                                                c4 = (c4.substring(1, c4.length()-1));
                                                                                                c5 = (c5.substring(1, c5.length()-1));
                                                                                                c6 = (c6.substring(1, c6.length()-1));
                                                                                                System.out.println(c1+c2+c3+c4+c5+c6);
                                                                                                Formulario form = new Formulario(c1, c2, c3, c4, c5, c6);
                                                                                                form.setListaComponentes((ArrayList<Componente>) listaComponentes.clone());
                                                                                                listaFormularios.add(form);
                                                                                                listaComponentes.clear();
                                                                                                c1 = null; c2 = null; c3 = null; c4 = null; c5 = null; c6 = null;
                                                                                             
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("valores_formulariosdb",2, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // acciones_formulariosdb ::= opciones_formulariosdb COMA acciones_formulariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("acciones_formulariosdb",3, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // acciones_formulariosdb ::= opciones_formulariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("acciones_formulariosdb",3, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // opciones_formulariosdb ::= ID_FORMULARIO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 c1 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // opciones_formulariosdb ::= TITULO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 c2 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // opciones_formulariosdb ::= NOMBRE PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 c3 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // opciones_formulariosdb ::= TEMA PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 c4 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // opciones_formulariosdb ::= USUARIO_CREACION PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 c5 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // opciones_formulariosdb ::= FECHA_CREACION PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 c6 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // opciones_formulariosdb ::= ESTRUCTURA PUNTOS PARENT_A estructura_forms_p PARENT_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // opciones_formulariosdb ::= DATOS_RECOPILADOS PUNTOS PARENT_A datos_forms PARENT_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // estructura_forms_p ::= estructura_forms COMA estructura_forms_p 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("estructura_forms_p",14, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // estructura_forms_p ::= estructura_forms 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("estructura_forms_p",14, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // estructura_forms ::= LLAVE_A instruccion_estructura_forms LLAVE_C 
            {
              Object RESULT =null;
		
                                                                            p1 = (p1.substring(1, p1.length()-1));
                                                                            p3 = (p3.substring(1, p3.length()-1));
                                                                            p4 = (p4.substring(1, p4.length()-1));
                                                                            p5 = (p5.substring(1, p5.length()-1));
                                                                            System.out.println("Probando p1");
                                                                            System.out.println(p1);
                                                                            Componente compo = new Componente(p1, p3, p4, p5);
                                                                            if(p2 != null) {
                                                                                compo.setNombreCampo(p2.substring(1, p2.length()-1));
                                                                            }
                                                                            if(p6 != null) {
                                                                                compo.setAlineacion(p6.substring(1, p6.length()-1));
                                                                            }
                                                                            if(p7 != null) {
                                                                                compo.setRequerido(p7.substring(1, p7.length()-1));
                                                                                }
                                                                            if(p8 != null) {
                                                                                compo.setOpciones(p8.substring(1, p8.length()-1));
                                                                            }
                                                                            if(p9 != null) {
                                                                                compo.setFilas(Integer.parseInt(p9.substring(1, p9.length()-1)));
                                                                            }
                                                                            if(p10 != null) {
                                                                                compo.setColumnas(Integer.parseInt(p10.substring(1, p10.length()-1)));
                                                                            }
                                                                            if(p11 != null) {
                                                                                compo.setUrl(p11.substring(1, p11.length()-1));
                                                                            }
                                                                            listaComponentes.add(compo);
                                                                            p1 = null; p2 = null; p3 = null; p4 = null; p5 = null; p6 = null; p7 = null; p8 = null; p9 = null; p10 = null; p11 = null;
                                                                        
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("estructura_forms",5, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // estructura_forms ::= LLAVE_A error LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("estructura_forms",5, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // instruccion_estructura_forms ::= opciones_estructura_forms COMA instruccion_estructura_forms 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_estructura_forms",7, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // instruccion_estructura_forms ::= 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_estructura_forms",7, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // opciones_estructura_forms ::= ID_COMPONENTE_N PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p1 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // opciones_estructura_forms ::= NOMBRE_CAMPO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p2 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // opciones_estructura_forms ::= FORMULARIO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p3 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // opciones_estructura_forms ::= CLASE PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p4 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // opciones_estructura_forms ::= TEXTO_VISIBLE PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p5 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // opciones_estructura_forms ::= INDICE PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // opciones_estructura_forms ::= ALINEACION PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p6 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // opciones_estructura_forms ::= REQUERIDO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p7 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // opciones_estructura_forms ::= OPCIONES PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p8 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // opciones_estructura_forms ::= FILAS PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p9 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // opciones_estructura_forms ::= COLUMNAS PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p10 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // opciones_estructura_forms ::= URL PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int entleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int entright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object ent = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p11 = ent.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // datos_forms ::= LLAVE_A instruccion_datos_forms LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("datos_forms",6, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // instruccion_datos_forms ::= opciones_datos_forms COMA instruccion_datos_forms 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_datos_forms",9, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // instruccion_datos_forms ::= opciones_datos_forms 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_datos_forms",9, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // opciones_datos_forms ::= NOMBRE_CAMPO_N PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_datos_forms",10, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // opciones_datos_forms ::= REGISTRO_N PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_datos_forms",10, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // instruccion_usuariosdb ::= valores_usuariosdb COMA instruccion_usuariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_usuariosdb",11, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // instruccion_usuariosdb ::= valores_usuariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_usuariosdb",11, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // valores_usuariosdb ::= LLAVE_A valores_usuariosdb_p LLAVE_C 
            {
              Object RESULT =null;
		
                                                                                p1 = p1.substring(1, p1.length()-1);
                                                                                p2 = p2.substring(1, p2.length()-1);
                                                                                p3 = p3.substring(1, p3.length()-1);
                                                                                Usuario user = new Usuario(p1, p2, p3);
                                                                                listaUsuarios.add(user);
                                                                                p1 = null; p2 = null; p3 = null;
                                                                            
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("valores_usuariosdb",12, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // valores_usuariosdb ::= LLAVE_A error LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("valores_usuariosdb",12, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // valores_usuariosdb_p ::= opciones_usuariosdb COMA valores_usuariosdb_p 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("valores_usuariosdb_p",13, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // valores_usuariosdb_p ::= opciones_usuariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("valores_usuariosdb_p",13, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // opciones_usuariosdb ::= USUARIO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int paraleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int pararight = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object para = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p1 = para.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_usuariosdb",15, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // opciones_usuariosdb ::= PASSWORD PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int paraleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int pararight = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object para = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p2 = para.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_usuariosdb",15, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // opciones_usuariosdb ::= FECHA_CREACION PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int paraleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int pararight = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object para = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p3 = para.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_usuariosdb",15, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserGuardado$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserGuardado$do_action(
    int                        CUP$ParserGuardado$act_num,
    java_cup.runtime.lr_parser CUP$ParserGuardado$parser,
    java.util.Stack            CUP$ParserGuardado$stack,
    int                        CUP$ParserGuardado$top)
    throws java.lang.Exception
    {
              return CUP$ParserGuardado$do_action_part00000000(
                               CUP$ParserGuardado$act_num,
                               CUP$ParserGuardado$parser,
                               CUP$ParserGuardado$stack,
                               CUP$ParserGuardado$top);
    }
}

}
