
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.formulariosweb.analizadores.db;

import com.froi.formulariosweb.entidadesfundamentales.*;
import java.util.ArrayList;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserGuardado extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ParserGuardadoSym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserGuardado() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserGuardado(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserGuardado(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\057\000\002\002\004\000\002\002\006\000\002\002" +
    "\006\000\002\002\006\000\002\003\005\000\002\003\003" +
    "\000\002\004\005\000\002\005\005\000\002\005\003\000" +
    "\002\006\005\000\002\006\005\000\002\006\005\000\002" +
    "\006\005\000\002\006\005\000\002\006\007\000\002\006" +
    "\007\000\002\020\005\000\002\020\003\000\002\007\005" +
    "\000\002\007\005\000\002\011\005\000\002\011\003\000" +
    "\002\012\005\000\002\012\005\000\002\012\005\000\002" +
    "\012\005\000\002\012\005\000\002\012\005\000\002\012" +
    "\005\000\002\012\005\000\002\012\005\000\002\012\005" +
    "\000\002\012\005\000\002\010\005\000\002\013\005\000" +
    "\002\013\003\000\002\014\005\000\002\014\005\000\002" +
    "\015\005\000\002\015\003\000\002\016\005\000\002\016" +
    "\005\000\002\017\005\000\002\017\003\000\002\021\005" +
    "\000\002\021\005\000\002\021\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\173\000\006\006\004\007\005\001\002\000\004\027" +
    "\041\001\002\000\004\027\010\001\002\000\004\002\007" +
    "\001\002\000\004\002\001\001\002\000\006\003\011\004" +
    "\014\001\002\000\004\030\040\001\002\000\006\030\uffda" +
    "\031\036\001\002\000\004\030\035\001\002\000\012\003" +
    "\015\010\016\011\021\017\017\001\002\000\004\005\034" +
    "\001\002\000\004\032\032\001\002\000\004\032\030\001" +
    "\002\000\006\005\uffd6\031\026\001\002\000\004\032\024" +
    "\001\002\000\004\005\023\001\002\000\006\030\uffd9\031" +
    "\uffd9\001\002\000\004\064\025\001\002\000\006\005\uffd4" +
    "\031\uffd4\001\002\000\010\010\016\011\021\017\017\001" +
    "\002\000\004\005\uffd7\001\002\000\004\064\031\001\002" +
    "\000\006\005\uffd3\031\uffd3\001\002\000\004\064\033\001" +
    "\002\000\006\005\uffd5\031\uffd5\001\002\000\006\030\uffd8" +
    "\031\uffd8\001\002\000\004\002\uffff\001\002\000\004\004" +
    "\014\001\002\000\004\030\uffdb\001\002\000\004\002\ufffe" +
    "\001\002\000\004\004\043\001\002\000\004\030\175\001" +
    "\002\000\020\012\050\013\052\014\056\015\054\016\047" +
    "\020\053\021\051\001\002\000\010\005\ufffc\030\ufffc\031" +
    "\045\001\002\000\004\004\043\001\002\000\006\005\ufffd" +
    "\030\ufffd\001\002\000\004\032\173\001\002\000\004\032" +
    "\171\001\002\000\004\032\151\001\002\000\004\032\147" +
    "\001\002\000\004\032\067\001\002\000\004\032\065\001" +
    "\002\000\004\005\064\001\002\000\004\032\062\001\002" +
    "\000\006\005\ufff9\031\060\001\002\000\004\004\043\001" +
    "\002\000\004\005\ufffa\001\002\000\004\064\063\001\002" +
    "\000\006\005\ufff6\031\ufff6\001\002\000\010\005\ufffb\030" +
    "\ufffb\031\ufffb\001\002\000\004\064\066\001\002\000\006" +
    "\005\ufff5\031\ufff5\001\002\000\004\027\070\001\002\000" +
    "\004\004\073\001\002\000\004\030\146\001\002\000\006" +
    "\030\ufff0\031\144\001\002\000\032\003\106\023\074\025" +
    "\104\026\103\033\102\034\107\035\100\036\076\037\075" +
    "\040\101\041\105\065\077\001\002\000\004\032\142\001" +
    "\002\000\004\032\140\001\002\000\004\032\136\001\002" +
    "\000\004\032\134\001\002\000\004\032\132\001\002\000" +
    "\004\032\130\001\002\000\004\032\126\001\002\000\004" +
    "\032\124\001\002\000\004\032\122\001\002\000\004\032" +
    "\120\001\002\000\004\005\117\001\002\000\004\032\115" +
    "\001\002\000\004\005\114\001\002\000\006\005\uffec\031" +
    "\112\001\002\000\030\023\074\025\104\026\103\033\102" +
    "\034\107\035\100\036\076\037\075\040\101\041\105\065" +
    "\077\001\002\000\004\005\uffed\001\002\000\006\030\uffef" +
    "\031\uffef\001\002\000\004\064\116\001\002\000\006\005" +
    "\uffe6\031\uffe6\001\002\000\006\030\uffee\031\uffee\001\002" +
    "\000\004\064\121\001\002\000\006\005\uffe1\031\uffe1\001" +
    "\002\000\004\064\123\001\002\000\006\005\uffe9\031\uffe9" +
    "\001\002\000\004\064\125\001\002\000\006\005\uffe8\031" +
    "\uffe8\001\002\000\004\064\127\001\002\000\006\005\uffe7" +
    "\031\uffe7\001\002\000\004\064\131\001\002\000\006\005" +
    "\uffe2\031\uffe2\001\002\000\004\064\133\001\002\000\006" +
    "\005\uffe5\031\uffe5\001\002\000\004\064\135\001\002\000" +
    "\006\005\uffeb\031\uffeb\001\002\000\004\064\137\001\002" +
    "\000\006\005\uffe4\031\uffe4\001\002\000\004\064\141\001" +
    "\002\000\006\005\uffe3\031\uffe3\001\002\000\004\064\143" +
    "\001\002\000\006\005\uffea\031\uffea\001\002\000\004\004" +
    "\073\001\002\000\004\030\ufff1\001\002\000\006\005\ufff3" +
    "\031\ufff3\001\002\000\004\064\150\001\002\000\006\005" +
    "\ufff7\031\ufff7\001\002\000\004\027\152\001\002\000\004" +
    "\004\154\001\002\000\004\030\170\001\002\000\006\062" +
    "\156\063\160\001\002\000\004\005\167\001\002\000\004" +
    "\032\165\001\002\000\006\005\uffde\031\163\001\002\000" +
    "\004\032\161\001\002\000\004\064\162\001\002\000\006" +
    "\005\uffdc\031\uffdc\001\002\000\006\062\156\063\160\001" +
    "\002\000\004\005\uffdf\001\002\000\004\064\166\001\002" +
    "\000\006\005\uffdd\031\uffdd\001\002\000\004\030\uffe0\001" +
    "\002\000\006\005\ufff2\031\ufff2\001\002\000\004\064\172" +
    "\001\002\000\006\005\ufff8\031\ufff8\001\002\000\004\064" +
    "\174\001\002\000\006\005\ufff4\031\ufff4\001\002\000\004" +
    "\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\173\000\004\002\005\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\015\012\016\011\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\017\021\021\017\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\017" +
    "\026\021\017\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\015\036\016\011" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\003" +
    "\041\004\043\001\001\000\002\001\001\000\006\005\054" +
    "\006\056\001\001\000\002\001\001\000\006\003\045\004" +
    "\043\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\003\060\004\043\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\007\071\020\070\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\011\107\012\110\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\011\112\012\110\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\007\071\020\144" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\010\152" +
    "\001\001\000\002\001\001\000\006\013\154\014\156\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\013\163\014\156\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserGuardado$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserGuardado$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserGuardado$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private ArrayList<Usuario> listaUsuarios;
    private ArrayList<Formulario> listaFormularios;
    private String p1, p2, p3, p4, p5, p6, p7, p8;
    
    public ParserGuardado(GuardadoLexer lexer, ArrayList<Usuario> listaUsuarios, ArrayList<Formulario> listaFormularios) {
        super(lexer);
        this.listaUsuarios = listaUsuarios;
        this.listaFormularios = listaFormularios;
    }
    public void report_error(String message, Object info) {
        System.out.println("reporterror");
    }
    public void report_fatal_error(String message, Object info) {
        System.out.println("reportfatal " + info);
    }
    @Override
    public void syntax_error(Symbol s) {
        System.out.println("linea: " + s.left + "   columna: " + s.right);
    }
    protected int error_sync_size() {
        return 1;
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserGuardado$actions {
  private final ParserGuardado parser;

  /** Constructor */
  CUP$ParserGuardado$actions(ParserGuardado parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserGuardado$do_action_part00000000(
    int                        CUP$ParserGuardado$act_num,
    java_cup.runtime.lr_parser CUP$ParserGuardado$parser,
    java.util.Stack            CUP$ParserGuardado$stack,
    int                        CUP$ParserGuardado$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserGuardado$result;

      /* select the action based on the action number */
      switch (CUP$ParserGuardado$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)).value;
		RESULT = start_val;
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-1)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserGuardado$parser.done_parsing();
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= DB_FORMULARIOS PARENT_A instruccion_formulariosdb PARENT_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= DB_USUARIOS PARENT_A instruccion_usuariosdb PARENT_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // inicio ::= DB_USUARIOS PARENT_A error PARENT_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-3)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion_formulariosdb ::= valores_formulariosdb COMA instruccion_formulariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_formulariosdb",1, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion_formulariosdb ::= valores_formulariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_formulariosdb",1, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // valores_formulariosdb ::= LLAVE_A acciones_formulariosdb LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("valores_formulariosdb",2, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // acciones_formulariosdb ::= opciones_formulariosdb COMA instruccion_formulariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("acciones_formulariosdb",3, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // acciones_formulariosdb ::= opciones_formulariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("acciones_formulariosdb",3, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // opciones_formulariosdb ::= ID_FORMULARIO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // opciones_formulariosdb ::= TITULO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // opciones_formulariosdb ::= NOMBRE PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // opciones_formulariosdb ::= TEMA PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // opciones_formulariosdb ::= USUARIO_CREACION PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // opciones_formulariosdb ::= ESTRUCTURA PUNTOS PARENT_A estructura_forms_p PARENT_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // opciones_formulariosdb ::= DATOS_RECOPILADOS PUNTOS PARENT_A datos_forms PARENT_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_formulariosdb",4, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-4)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // estructura_forms_p ::= estructura_forms COMA estructura_forms_p 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("estructura_forms_p",14, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // estructura_forms_p ::= estructura_forms 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("estructura_forms_p",14, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // estructura_forms ::= LLAVE_A instruccion_estructura_forms LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("estructura_forms",5, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // estructura_forms ::= LLAVE_A error LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("estructura_forms",5, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // instruccion_estructura_forms ::= opciones_estructura_forms COMA instruccion_estructura_forms 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_estructura_forms",7, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // instruccion_estructura_forms ::= opciones_estructura_forms 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_estructura_forms",7, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // opciones_estructura_forms ::= ID_COMPONENTE_N PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // opciones_estructura_forms ::= NOMBRE_CAMPO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // opciones_estructura_forms ::= CLASE PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // opciones_estructura_forms ::= INDICE PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // opciones_estructura_forms ::= TEXTO_VISIBLE PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // opciones_estructura_forms ::= ALINEACION PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // opciones_estructura_forms ::= REQUERIDO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // opciones_estructura_forms ::= OPCIONES PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // opciones_estructura_forms ::= FILAS PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // opciones_estructura_forms ::= COLUMNAS PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // opciones_estructura_forms ::= URL PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_estructura_forms",8, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // datos_forms ::= LLAVE_A instruccion_datos_forms LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("datos_forms",6, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // instruccion_datos_forms ::= opciones_datos_forms COMA instruccion_datos_forms 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_datos_forms",9, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // instruccion_datos_forms ::= opciones_datos_forms 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_datos_forms",9, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // opciones_datos_forms ::= NOMBRE_CAMPO_N PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_datos_forms",10, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // opciones_datos_forms ::= REGISTRO_N PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_datos_forms",10, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // instruccion_usuariosdb ::= valores_usuariosdb COMA instruccion_usuariosdb 
            {
              Object RESULT =null;
		 System.out.println("Instruccion1"); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_usuariosdb",11, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // instruccion_usuariosdb ::= valores_usuariosdb 
            {
              Object RESULT =null;
		 System.out.println("Instruccion2"); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("instruccion_usuariosdb",11, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // valores_usuariosdb ::= LLAVE_A valores_usuariosdb_p LLAVE_C 
            {
              Object RESULT =null;
		
                                                                                System.out.println("aqui aun funcionan las cosas");
                                                                                p1 = p1.substring(1, p1.length()-1);
                                                                                p2 = p2.substring(1, p2.length()-1);
                                                                                p3 = p3.substring(1, p3.length()-1);
                                                                                Usuario user = new Usuario(p1, p2, p3);
                                                                                listaUsuarios.add(user);
                                                                                p1 = null; p2 = null; p3 = null;
                                                                                System.out.println("Si se registró el usuario");
                                                                            
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("valores_usuariosdb",12, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // valores_usuariosdb ::= LLAVE_A error LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("valores_usuariosdb",12, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // valores_usuariosdb_p ::= opciones_usuariosdb COMA valores_usuariosdb_p 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("valores_usuariosdb_p",13, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // valores_usuariosdb_p ::= opciones_usuariosdb 
            {
              Object RESULT =null;

              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("valores_usuariosdb_p",13, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // opciones_usuariosdb ::= USUARIO PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int paraleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int pararight = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object para = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p1 = para.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_usuariosdb",15, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // opciones_usuariosdb ::= PASSWORD PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int paraleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int pararight = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object para = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p2 = para.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_usuariosdb",15, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // opciones_usuariosdb ::= FECHA_CREACION PUNTOS ALLCHARACTERS 
            {
              Object RESULT =null;
		int paraleft = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).left;
		int pararight = ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()).right;
		Object para = (Object)((java_cup.runtime.Symbol) CUP$ParserGuardado$stack.peek()).value;
		 p3 = para.toString(); 
              CUP$ParserGuardado$result = parser.getSymbolFactory().newSymbol("opciones_usuariosdb",15, ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.elementAt(CUP$ParserGuardado$top-2)), ((java_cup.runtime.Symbol)CUP$ParserGuardado$stack.peek()), RESULT);
            }
          return CUP$ParserGuardado$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserGuardado$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserGuardado$do_action(
    int                        CUP$ParserGuardado$act_num,
    java_cup.runtime.lr_parser CUP$ParserGuardado$parser,
    java.util.Stack            CUP$ParserGuardado$stack,
    int                        CUP$ParserGuardado$top)
    throws java.lang.Exception
    {
              return CUP$ParserGuardado$do_action_part00000000(
                               CUP$ParserGuardado$act_num,
                               CUP$ParserGuardado$parser,
                               CUP$ParserGuardado$stack,
                               CUP$ParserGuardado$top);
    }
}

}
