
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.formulariosweb.analizadores.codigoindigo;

/** CUP generated class containing symbol constants. */
public class ParserReportesSym {
  /* terminals */
  public static final int WHERE = 6;
  public static final int AND = 7;
  public static final int CADENA_CONSULTA = 22;
  public static final int SELECT = 2;
  public static final int OR = 8;
  public static final int IGUAL = 12;
  public static final int MENOR_IGUAL = 13;
  public static final int NOT = 9;
  public static final int FLECHA = 5;
  public static final int MAYOR_IGUAL = 14;
  public static final int MAYOR_QUE = 11;
  public static final int FORM = 4;
  public static final int COMA = 20;
  public static final int MENOR_QUE = 10;
  public static final int EOF = 0;
  public static final int DIFERENTE = 15;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 18;
  public static final int ALLCHARACTERSNOSPACE = 19;
  public static final int NUMERO_CONSULTA = 21;
  public static final int CORCHETE_C = 17;
  public static final int CORCHETE_A = 16;
  public static final int TO = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "TO",
  "FORM",
  "FLECHA",
  "WHERE",
  "AND",
  "OR",
  "NOT",
  "MENOR_QUE",
  "MAYOR_QUE",
  "IGUAL",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "DIFERENTE",
  "CORCHETE_A",
  "CORCHETE_C",
  "IDENTIFICADOR",
  "ALLCHARACTERSNOSPACE",
  "COMA",
  "NUMERO_CONSULTA",
  "CADENA_CONSULTA"
  };
}

