
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.pruebasgramaticas;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\165\000\002\002\004\000\002\002\003\000\002\002" +
    "\003\000\002\003\013\000\002\005\010\000\002\005\010" +
    "\000\002\005\010\000\002\005\010\000\002\005\010\000" +
    "\002\005\010\000\002\005\010\000\002\005\010\000\002" +
    "\005\010\000\002\005\010\000\002\005\005\000\002\006" +
    "\004\000\002\006\004\000\002\006\004\000\002\006\003" +
    "\000\002\007\004\000\002\010\004\000\002\014\005\000" +
    "\002\014\003\000\002\030\005\000\002\042\005\000\002" +
    "\042\003\000\002\054\005\000\002\054\005\000\002\015" +
    "\005\000\002\015\003\000\002\031\005\000\002\043\005" +
    "\000\002\043\003\000\002\055\005\000\002\055\005\000" +
    "\002\055\005\000\002\055\005\000\002\016\005\000\002" +
    "\016\003\000\002\032\005\000\002\056\005\000\002\017" +
    "\005\000\002\017\003\000\002\033\005\000\002\045\005" +
    "\000\002\045\003\000\002\057\005\000\002\057\005\000" +
    "\002\022\005\000\002\022\003\000\002\034\005\000\002" +
    "\046\005\000\002\046\003\000\002\060\005\000\002\060" +
    "\005\000\002\060\005\000\002\060\005\000\002\060\005" +
    "\000\002\060\005\000\002\026\005\000\002\026\003\000" +
    "\002\035\005\000\002\047\005\000\002\047\003\000\002" +
    "\061\005\000\002\020\005\000\002\020\003\000\002\036" +
    "\005\000\002\050\005\000\002\050\003\000\002\062\005" +
    "\000\002\062\005\000\002\062\005\000\002\062\005\000" +
    "\002\021\005\000\002\021\003\000\002\037\005\000\002" +
    "\051\005\000\002\051\003\000\002\063\005\000\002\063" +
    "\005\000\002\063\005\000\002\063\005\000\002\063\004" +
    "\000\002\063\005\000\002\063\005\000\002\063\005\000" +
    "\002\063\005\000\002\063\005\000\002\063\005\000\002" +
    "\011\003\000\002\011\003\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\011\003\000\002\013\003\000\002\013\003\000" +
    "\002\013\003\000\002\013\003\000\002\023\005\000\002" +
    "\023\003\000\002\040\005\000\002\052\005\000\002\052" +
    "\003\000\002\064\005\000\002\064\005\000\002\024\005" +
    "\000\002\024\003\000\002\041\005\000\002\053\005\000" +
    "\002\053\003\000\002\065\005\000\002\065\005\000\002" +
    "\065\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u0122\000\004\004\004\001\002\000\004\007\011\001" +
    "\002\000\004\002\uffff\001\002\000\004\002\000\001\002" +
    "\000\004\002\010\001\002\000\004\002\001\001\002\000" +
    "\004\043\012\001\002\000\004\010\013\001\002\000\030" +
    "\045\024\051\015\055\014\056\017\066\020\067\026\070" +
    "\021\072\025\107\016\110\023\111\022\001\002\000\006" +
    "\003\035\005\034\001\002\000\006\003\035\005\034\001" +
    "\002\000\006\003\035\005\034\001\002\000\006\003\035" +
    "\005\034\001\002\000\006\003\035\005\034\001\002\000" +
    "\006\003\035\005\034\001\002\000\006\003\035\005\034" +
    "\001\002\000\006\003\035\005\034\001\002\000\006\003" +
    "\035\005\034\001\002\000\006\003\035\005\034\001\002" +
    "\000\006\003\035\005\034\001\002\000\004\004\030\001" +
    "\002\000\004\044\031\001\002\000\004\007\032\001\002" +
    "\000\004\005\033\001\002\000\004\002\ufffe\001\002\000" +
    "\006\003\067\020\070\001\002\000\012\020\066\046\uffef" +
    "\071\uffef\073\uffef\001\002\000\004\046\037\001\002\000" +
    "\004\010\040\001\002\000\004\012\065\001\002\000\004" +
    "\020\044\001\002\000\004\013\063\001\002\000\006\013" +
    "\uffd7\014\060\001\002\000\006\047\045\050\050\001\002" +
    "\000\004\010\056\001\002\000\004\021\055\001\002\000" +
    "\006\014\053\021\uffd4\001\002\000\004\010\051\001\002" +
    "\000\004\023\052\001\002\000\006\014\uffd2\021\uffd2\001" +
    "\002\000\006\047\045\050\050\001\002\000\004\021\uffd5" +
    "\001\002\000\006\013\uffd6\014\uffd6\001\002\000\004\023" +
    "\057\001\002\000\006\014\uffd3\021\uffd3\001\002\000\004" +
    "\020\044\001\002\000\004\013\uffd8\001\002\000\004\004" +
    "\ufffa\001\002\000\004\021\064\001\002\000\004\004\uffed" +
    "\001\002\000\004\020\uffee\001\002\000\010\046\ufff1\071" +
    "\ufff1\073\ufff1\001\002\000\010\046\ufff0\071\ufff0\073\ufff0" +
    "\001\002\000\010\046\ufff2\071\ufff2\073\ufff2\001\002\000" +
    "\004\073\072\001\002\000\004\010\040\001\002\000\004" +
    "\020\076\001\002\000\006\013\uffb6\014\161\001\002\000" +
    "\004\013\063\001\002\000\030\057\110\074\077\075\103" +
    "\076\107\100\106\101\112\102\104\103\101\104\100\105" +
    "\105\106\111\001\002\000\004\010\156\001\002\000\004" +
    "\010\154\001\002\000\004\010\152\001\002\000\004\021" +
    "\151\001\002\000\004\010\147\001\002\000\004\010\145" +
    "\001\002\000\004\010\143\001\002\000\004\023\142\001" +
    "\002\000\004\010\130\001\002\000\004\010\126\001\002" +
    "\000\004\010\124\001\002\000\004\010\116\001\002\000" +
    "\006\014\114\021\uffb3\001\002\000\030\057\110\074\077" +
    "\075\103\076\107\100\106\101\112\102\104\103\101\104" +
    "\100\105\105\106\111\001\002\000\004\021\uffb4\001\002" +
    "\000\012\034\122\035\120\036\117\037\123\001\002\000" +
    "\006\014\uff9d\021\uff9d\001\002\000\006\014\uff9e\021\uff9e" +
    "\001\002\000\006\014\uffad\021\uffad\001\002\000\006\014" +
    "\uff9f\021\uff9f\001\002\000\006\014\uff9c\021\uff9c\001\002" +
    "\000\004\023\125\001\002\000\006\014\uffa8\021\uffa8\001" +
    "\002\000\004\022\127\001\002\000\006\014\uffb2\021\uffb2" +
    "\001\002\000\022\112\133\113\134\114\140\115\137\116" +
    "\135\117\136\120\141\121\131\001\002\000\006\014\uffa0" +
    "\021\uffa0\001\002\000\006\014\uffaf\021\uffaf\001\002\000" +
    "\006\014\uffa7\021\uffa7\001\002\000\006\014\uffa6\021\uffa6" +
    "\001\002\000\006\014\uffa3\021\uffa3\001\002\000\006\014" +
    "\uffa2\021\uffa2\001\002\000\006\014\uffa4\021\uffa4\001\002" +
    "\000\006\014\uffa5\021\uffa5\001\002\000\006\014\uffa1\021" +
    "\uffa1\001\002\000\006\014\uffae\021\uffae\001\002\000\004" +
    "\031\144\001\002\000\006\014\uffa9\021\uffa9\001\002\000" +
    "\002\001\002\000\006\014\uffac\021\uffac\001\002\000\004" +
    "\023\150\001\002\000\006\014\uffb0\021\uffb0\001\002\000" +
    "\006\013\uffb5\014\uffb5\001\002\000\004\040\153\001\002" +
    "\000\006\014\uffab\021\uffab\001\002\000\004\031\155\001" +
    "\002\000\006\014\uffaa\021\uffaa\001\002\000\004\023\157" +
    "\001\002\000\006\014\uffb1\021\uffb1\001\002\000\004\004" +
    "\ufff6\001\002\000\004\020\076\001\002\000\004\013\uffb7" +
    "\001\002\000\004\046\164\001\002\000\004\010\040\001" +
    "\002\000\004\020\170\001\002\000\004\013\063\001\002" +
    "\000\006\013\uffeb\014\204\001\002\000\006\047\172\050" +
    "\174\001\002\000\004\021\203\001\002\000\004\010\201" +
    "\001\002\000\006\014\177\021\uffe8\001\002\000\004\010" +
    "\175\001\002\000\004\023\176\001\002\000\006\014\uffe6" +
    "\021\uffe6\001\002\000\006\047\172\050\174\001\002\000" +
    "\004\021\uffe9\001\002\000\004\023\202\001\002\000\006" +
    "\014\uffe7\021\uffe7\001\002\000\006\013\uffea\014\uffea\001" +
    "\002\000\004\020\170\001\002\000\004\013\uffec\001\002" +
    "\000\004\004\ufffd\001\002\000\004\073\210\001\002\000" +
    "\004\010\040\001\002\000\004\020\214\001\002\000\006" +
    "\013\uff93\014\232\001\002\000\004\013\063\001\002\000" +
    "\032\057\110\074\077\075\217\076\107\077\220\100\106" +
    "\101\112\102\104\103\101\104\100\105\105\106\111\001" +
    "\002\000\004\021\230\001\002\000\006\014\226\021\uff90" +
    "\001\002\000\004\010\224\001\002\000\004\010\222\001" +
    "\002\000\006\014\uff8d\021\uff8d\001\002\000\004\031\223" +
    "\001\002\000\006\014\uff8e\021\uff8e\001\002\000\006\022" +
    "\225\023\150\001\002\000\006\014\uff8f\021\uff8f\001\002" +
    "\000\032\057\110\074\077\075\217\076\107\077\220\100" +
    "\106\101\112\102\104\103\101\104\100\105\105\106\111" +
    "\001\002\000\004\021\uff91\001\002\000\006\013\uff92\014" +
    "\uff92\001\002\000\004\004\ufff4\001\002\000\004\020\214" +
    "\001\002\000\004\013\uff94\001\002\000\004\071\235\001" +
    "\002\000\004\004\ufff3\001\002\000\004\071\237\001\002" +
    "\000\004\010\040\001\002\000\004\020\242\001\002\000" +
    "\004\013\063\001\002\000\012\057\246\060\251\061\252" +
    "\062\247\001\002\000\006\013\uffbf\014\244\001\002\000" +
    "\004\020\242\001\002\000\004\013\uffc0\001\002\000\004" +
    "\010\265\001\002\000\004\010\263\001\002\000\006\014" +
    "\261\021\uffbc\001\002\000\004\010\257\001\002\000\004" +
    "\010\255\001\002\000\004\021\254\001\002\000\006\013" +
    "\uffbe\014\uffbe\001\002\000\004\023\256\001\002\000\006" +
    "\014\uffb9\021\uffb9\001\002\000\004\023\260\001\002\000" +
    "\006\014\uffba\021\uffba\001\002\000\012\057\246\060\251" +
    "\061\252\062\247\001\002\000\004\021\uffbd\001\002\000" +
    "\004\026\264\001\002\000\006\014\uffb8\021\uffb8\001\002" +
    "\000\004\022\266\001\002\000\006\014\uffbb\021\uffbb\001" +
    "\002\000\004\004\ufff7\001\002\000\004\071\271\001\002" +
    "\000\004\010\040\001\002\000\004\020\275\001\002\000" +
    "\004\013\063\001\002\000\006\013\uffc5\014\306\001\002" +
    "\000\004\057\276\001\002\000\004\010\304\001\002\000" +
    "\006\014\302\021\uffc2\001\002\000\004\021\301\001\002" +
    "\000\006\013\uffc4\014\uffc4\001\002\000\004\057\276\001" +
    "\002\000\004\021\uffc3\001\002\000\004\022\305\001\002" +
    "\000\006\014\uffc1\021\uffc1\001\002\000\004\020\275\001" +
    "\002\000\004\013\uffc6\001\002\000\004\004\ufff8\001\002" +
    "\000\004\071\312\001\002\000\004\010\040\001\002\000" +
    "\004\020\316\001\002\000\004\013\063\001\002\000\006" +
    "\013\uffd0\014\346\001\002\000\016\057\317\060\321\061" +
    "\325\062\320\063\326\065\324\001\002\000\004\010\344" +
    "\001\002\000\004\010\342\001\002\000\004\010\340\001" +
    "\002\000\004\021\337\001\002\000\006\014\335\021\uffcd" +
    "\001\002\000\004\010\333\001\002\000\004\010\331\001" +
    "\002\000\004\010\327\001\002\000\004\023\330\001\002" +
    "\000\006\014\uffc8\021\uffc8\001\002\000\004\023\332\001" +
    "\002\000\006\014\uffca\021\uffca\001\002\000\004\025\334" +
    "\001\002\000\006\014\uffc7\021\uffc7\001\002\000\016\057" +
    "\317\060\321\061\325\062\320\063\326\065\324\001\002" +
    "\000\004\021\uffce\001\002\000\006\013\uffcf\014\uffcf\001" +
    "\002\000\004\023\341\001\002\000\006\014\uffcb\021\uffcb" +
    "\001\002\000\004\026\343\001\002\000\006\014\uffc9\021" +
    "\uffc9\001\002\000\004\022\345\001\002\000\006\014\uffcc" +
    "\021\uffcc\001\002\000\004\020\316\001\002\000\004\013" +
    "\uffd1\001\002\000\004\004\ufff9\001\002\000\004\073\352" +
    "\001\002\000\004\010\040\001\002\000\004\020\356\001" +
    "\002\000\004\013\063\001\002\000\006\013\uff9a\014\372" +
    "\001\002\000\006\057\357\075\360\001\002\000\004\010" +
    "\370\001\002\000\004\010\366\001\002\000\004\021\365" +
    "\001\002\000\006\014\363\021\uff97\001\002\000\006\057" +
    "\357\075\360\001\002\000\004\021\uff98\001\002\000\006" +
    "\013\uff99\014\uff99\001\002\000\004\022\367\001\002\000" +
    "\006\014\uff95\021\uff95\001\002\000\004\022\371\001\002" +
    "\000\006\014\uff96\021\uff96\001\002\000\004\020\356\001" +
    "\002\000\004\013\uff9b\001\002\000\004\004\ufff5\001\002" +
    "\000\004\046\376\001\002\000\004\010\040\001\002\000" +
    "\004\020\u0102\001\002\000\006\013\uffe4\014\u0115\001\002" +
    "\000\004\013\063\001\002\000\012\052\u0103\053\u0106\054" +
    "\u0105\064\u0107\001\002\000\004\010\u0112\001\002\000\004" +
    "\021\u0111\001\002\000\004\010\u010f\001\002\000\004\010" +
    "\u010d\001\002\000\004\010\u010b\001\002\000\006\014\u0109" +
    "\021\uffe1\001\002\000\012\052\u0103\053\u0106\054\u0105\064" +
    "\u0107\001\002\000\004\021\uffe2\001\002\000\004\023\u010c" +
    "\001\002\000\006\014\uffdf\021\uffdf\001\002\000\004\023" +
    "\u010e\001\002\000\006\014\uffde\021\uffde\001\002\000\004" +
    "\025\u0110\001\002\000\006\014\uffdd\021\uffdd\001\002\000" +
    "\006\013\uffe3\014\uffe3\001\002\000\004\023\u0113\001\002" +
    "\000\006\014\uffe0\021\uffe0\001\002\000\004\004\ufffc\001" +
    "\002\000\004\020\u0102\001\002\000\004\013\uffe5\001\002" +
    "\000\004\046\u0118\001\002\000\004\010\040\001\002\000" +
    "\004\020\u011c\001\002\000\004\013\063\001\002\000\006" +
    "\013\uffdb\014\u0122\001\002\000\004\047\u011e\001\002\000" +
    "\004\021\u0121\001\002\000\004\010\u011f\001\002\000\004" +
    "\023\u0120\001\002\000\004\021\uffd9\001\002\000\006\013" +
    "\uffda\014\uffda\001\002\000\004\020\u011c\001\002\000\004" +
    "\013\uffdc\001\002\000\004\004\ufffb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u0122\000\010\002\006\003\005\004\004\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\026\001\001\000\004\006\u0116\001\001" +
    "\000\004\006\374\001\001\000\004\006\350\001\001\000" +
    "\004\006\310\001\001\000\004\006\267\001\001\000\004" +
    "\006\235\001\001\000\004\006\233\001\001\000\004\006" +
    "\206\001\001\000\004\006\162\001\001\000\004\006\070" +
    "\001\001\000\004\006\035\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\040\001\001\000\002\001\001\000\006" +
    "\017\041\033\042\001\001\000\004\010\061\001\001\000" +
    "\002\001\001\000\006\045\045\057\046\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\045\053" +
    "\057\046\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\017\060\033\042" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\072\001\001\000\006\021\074\037\073\001\001" +
    "\000\002\001\001\000\004\010\157\001\001\000\006\051" +
    "\101\063\112\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\051\114\063\112\001\001" +
    "\000\002\001\001\000\004\013\120\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\131\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\012\145" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\021\161\037\073" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\164\001\001\000\006\014\165\030\166\001\001\000\004" +
    "\010\205\001\001\000\002\001\001\000\006\042\170\054" +
    "\172\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\042\177\054\172\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\014\204\030\166\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\007\210\001\001\000" +
    "\006\024\212\041\211\001\001\000\002\001\001\000\004" +
    "\010\230\001\001\000\010\053\214\063\220\065\215\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\053\226\063\220\065\215\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\024\232\041\211" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\007\237\001\001\000\006" +
    "\020\240\036\242\001\001\000\004\010\266\001\001\000" +
    "\006\050\252\062\247\001\001\000\002\001\001\000\006" +
    "\020\244\036\242\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\050\261\062\247\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\271\001\001\000\006\026\272\035\273\001\001" +
    "\000\004\010\307\001\001\000\002\001\001\000\006\047" +
    "\277\061\276\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\047\302\061" +
    "\276\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\026\306\035\273\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\007\312" +
    "\001\001\000\006\022\313\034\314\001\001\000\004\010" +
    "\347\001\001\000\002\001\001\000\006\046\321\060\322" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\046\335\060\322\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\022\346\034\314" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\352\001\001\000\006\023\353\040\354" +
    "\001\001\000\004\010\373\001\001\000\002\001\001\000" +
    "\006\052\360\064\361\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\052" +
    "\363\064\361\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\023\372\040\354\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\376\001\001\000\006\015\u0100\031\377\001\001\000\002" +
    "\001\001\000\004\010\u0113\001\001\000\006\043\u0103\055" +
    "\u0107\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\043\u0109\055\u0107\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\015\u0115\031\377\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\u0118\001\001\000\006\016" +
    "\u0119\032\u011a\001\001\000\004\010\u0123\001\001\000\002" +
    "\001\001\000\004\056\u011c\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\016\u0122\032\u011a\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    public void report_error(String message, Object info) {
        System.out.println("reporterror");
    }
    public void report_fatal_error(String message, Object info) {
        System.out.println("reportfatal " + info);
    }
    @Override
    public void syntax_error(Symbol s) {
        System.out.println("linea: " + s.left + "   columna: " + s.right);
    }
    protected int error_sync_size() {
        return 1;
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= solicitud 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= solicitudes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // solicitud ::= MENOR_QUE EXCLAMACION INI_SOLICITUD PUNTOS tipo_solicitud MENOR_QUE FIN_SOLICITUD EXCLAMACION MAYOR_QUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("solicitud",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // tipo_solicitud ::= CREAR_USUARIO apertura_instruccion_principal1 CREDENCIALES_USUARIO apertura_instruccion_principal2 instruccion_creacion_usuario cierre_instruccion_principal 
            {
              Object RESULT =null;
		 System.out.println("CREACION DE USUARIO"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // tipo_solicitud ::= MODIFICAR_USUARIO apertura_instruccion_principal1 CREDENCIALES_USUARIO apertura_instruccion_principal2 instruccion_modificacion_usuario cierre_instruccion_principal 
            {
              Object RESULT =null;
		 System.out.println("MODIFICACION DE USUARIO"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // tipo_solicitud ::= ELIMINAR_USUARIO apertura_instruccion_principal1 CREDENCIALES_USUARIO apertura_instruccion_principal2 instruccion_eliminacion_usuario cierre_instruccion_principal 
            {
              Object RESULT =null;
		 System.out.println("ELIMINACION DE USUARIO"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // tipo_solicitud ::= LOGIN_USUARIO apertura_instruccion_principal1 CREDENCIALES_USUARIO apertura_instruccion_principal2 instruccion_login_usuario cierre_instruccion_principal 
            {
              Object RESULT =null;
		 System.out.println("LOGIN USUARIO"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // tipo_solicitud ::= NUEVO_FORMULARIO apertura_instruccion_principal1 PARAMETROS_FORMULARIO apertura_instruccion_principal2 instruccion_nuevo_formulario cierre_instruccion_principal 
            {
              Object RESULT =null;
		 System.out.println("NUEVO FORMULARIO"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // tipo_solicitud ::= ELIMINAR_FORMULARIO apertura_instruccion_principal1 PARAMETROS_FORMULARIO apertura_instruccion_principal2 instruccion_eliminacion_formulario cierre_instruccion_principal 
            {
              Object RESULT =null;
		 System.out.println("ELIMINAR FORMULARIO"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // tipo_solicitud ::= MODIFICAR_FORMULARIO apertura_instruccion_principal1 PARAMETROS_FORMULARIO apertura_instruccion_principal2 instruccion_modificacion_formulario cierre_instruccion_principal 
            {
              Object RESULT =null;
		 System.out.println("MODIFICAR FORMULARIO"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // tipo_solicitud ::= AGREGAR_COMPONENTE apertura_instruccion_principal1 PARAMETROS_COMPONENTE apertura_instruccion_principal2 instruccion_agregar_componente cierre_instruccion_principal 
            {
              Object RESULT =null;
		 System.out.println("AGREGAR COMPONENTE"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // tipo_solicitud ::= ELIMINAR_COMPONENTE apertura_instruccion_principal1 PARAMETROS_COMPONENTE apertura_instruccion_principal2 instruccion_eliminacion_componente cierre_instruccion_principal 
            {
              Object RESULT =null;
		 System.out.println("ELIMINAR COMPONENTE"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // tipo_solicitud ::= MODIFICAR_COMPONENTE apertura_instruccion_principal1 PARAMETROS_COMPONENTE apertura_instruccion_principal2 instruccion_modificacion_componente cierre_instruccion_principal 
            {
              Object RESULT =null;
		 System.out.println("MODIFICAR COMPONENTE"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // tipo_solicitud ::= CONSULTAR_DATOS apertura_instruccion_principal1 PARAMETROS_FORMULARIO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_solicitud",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // apertura_instruccion_principal1 ::= MAYOR_QUE LLAVE_A 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("apertura_instruccion_principal1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // apertura_instruccion_principal1 ::= error LLAVE_A 
            {
              Object RESULT =null;
		 System.out.println("Falta >"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("apertura_instruccion_principal1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // apertura_instruccion_principal1 ::= MAYOR_QUE error 
            {
              Object RESULT =null;
		 System.out.println("Falta {"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("apertura_instruccion_principal1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // apertura_instruccion_principal1 ::= error 
            {
              Object RESULT =null;
		 System.out.println("Error en la expresion"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("apertura_instruccion_principal1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // apertura_instruccion_principal2 ::= PUNTOS CORCHETE_A 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("apertura_instruccion_principal2",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // cierre_instruccion_principal ::= CORCHETE_C LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cierre_instruccion_principal",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // instruccion_creacion_usuario ::= accion_crear_usuario COMA instruccion_creacion_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_creacion_usuario",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // instruccion_creacion_usuario ::= accion_crear_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_creacion_usuario",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // accion_crear_usuario ::= LLAVE_A accion_crear_usuario_p LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_crear_usuario",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // accion_crear_usuario_p ::= opciones_crear_usuario COMA accion_crear_usuario_p 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_crear_usuario_p",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // accion_crear_usuario_p ::= opciones_crear_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_crear_usuario_p",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // opciones_crear_usuario ::= USUARIO PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_crear_usuario",42, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // opciones_crear_usuario ::= PASSWORD PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_crear_usuario",42, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // instruccion_modificacion_usuario ::= accion_modificacion_usuario COMA instruccion_modificacion_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_modificacion_usuario",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // instruccion_modificacion_usuario ::= accion_modificacion_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_modificacion_usuario",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // accion_modificacion_usuario ::= LLAVE_A accion_modificacion_usuario_p LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_modificacion_usuario",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // accion_modificacion_usuario_p ::= opciones_modificacion_usuario COMA accion_modificacion_usuario_p 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_modificacion_usuario_p",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // accion_modificacion_usuario_p ::= opciones_modificacion_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_modificacion_usuario_p",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // opciones_modificacion_usuario ::= USUARIO_ANTIGUO PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_usuario",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // opciones_modificacion_usuario ::= USUARIO_NUEVO PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_usuario",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // opciones_modificacion_usuario ::= NUEVO_PASSWORD PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_usuario",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // opciones_modificacion_usuario ::= FECHA_MODIFICACION PUNTOS FECHA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_usuario",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // instruccion_eliminacion_usuario ::= accion_eliminacion_usuario COMA instruccion_eliminacion_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_eliminacion_usuario",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // instruccion_eliminacion_usuario ::= accion_eliminacion_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_eliminacion_usuario",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // accion_eliminacion_usuario ::= LLAVE_A opciones_eliminacion_usuario LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_eliminacion_usuario",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // opciones_eliminacion_usuario ::= USUARIO PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_eliminacion_usuario",44, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // instruccion_login_usuario ::= accion_login_usuario COMA instruccion_login_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_login_usuario",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // instruccion_login_usuario ::= accion_login_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_login_usuario",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // accion_login_usuario ::= LLAVE_A accion_login_usuario_p LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_login_usuario",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // accion_login_usuario_p ::= opciones_login_usuario COMA accion_login_usuario_p 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_login_usuario_p",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // accion_login_usuario_p ::= opciones_login_usuario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_login_usuario_p",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // opciones_login_usuario ::= USUARIO PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_login_usuario",45, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // opciones_login_usuario ::= PASSWORD PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_login_usuario",45, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // instruccion_nuevo_formulario ::= accion_nuevo_formulario COMA instruccion_nuevo_formulario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_nuevo_formulario",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // instruccion_nuevo_formulario ::= accion_nuevo_formulario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_nuevo_formulario",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // accion_nuevo_formulario ::= LLAVE_A accion_nuevo_formulario_p LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_nuevo_formulario",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // accion_nuevo_formulario_p ::= opciones_nuevo_formulario COMA accion_nuevo_formulario_p 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_nuevo_formulario_p",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // accion_nuevo_formulario_p ::= opciones_nuevo_formulario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_nuevo_formulario_p",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // opciones_nuevo_formulario ::= ID PUNTOS IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_nuevo_formulario",46, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // opciones_nuevo_formulario ::= TITULO PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_nuevo_formulario",46, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // opciones_nuevo_formulario ::= NOMBRE PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_nuevo_formulario",46, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // opciones_nuevo_formulario ::= TEMA PUNTOS THEME 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_nuevo_formulario",46, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // opciones_nuevo_formulario ::= USUARIO_CREACION PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_nuevo_formulario",46, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // opciones_nuevo_formulario ::= FECHA_CREACION PUNTOS FECHA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_nuevo_formulario",46, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // instruccion_eliminacion_formulario ::= accion_eliminacion_formulario COMA instruccion_eliminacion_formulario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_eliminacion_formulario",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // instruccion_eliminacion_formulario ::= accion_eliminacion_formulario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_eliminacion_formulario",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // accion_eliminacion_formulario ::= LLAVE_A accion_eliminacion_formulario_p LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_eliminacion_formulario",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // accion_eliminacion_formulario_p ::= opciones_eliminacion_formulario COMA accion_eliminacion_formulario_p 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_eliminacion_formulario_p",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // accion_eliminacion_formulario_p ::= opciones_eliminacion_formulario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_eliminacion_formulario_p",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // opciones_eliminacion_formulario ::= ID PUNTOS IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_eliminacion_formulario",47, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // instruccion_modificacion_formulario ::= accion_modificacion_formulario COMA instruccion_modificacion_formulario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_modificacion_formulario",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // instruccion_modificacion_formulario ::= accion_modificacion_formulario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_modificacion_formulario",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // accion_modificacion_formulario ::= LLAVE_A accion_modificacion_formulario_p LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_modificacion_formulario",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // accion_modificacion_formulario_p ::= opciones_modificacion_formulario COMA accion_modificacion_formulario_p 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_modificacion_formulario_p",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // accion_modificacion_formulario_p ::= opciones_modificacion_formulario 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_modificacion_formulario_p",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // opciones_modificacion_formulario ::= ID PUNTOS IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_formulario",48, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // opciones_modificacion_formulario ::= TITULO PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_formulario",48, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // opciones_modificacion_formulario ::= NOMBRE PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_formulario",48, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // opciones_modificacion_formulario ::= TEMA PUNTOS THEME 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_formulario",48, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // instruccion_agregar_componente ::= accion_agregar_componente COMA instruccion_agregar_componente 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_agregar_componente",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // instruccion_agregar_componente ::= accion_agregar_componente 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_agregar_componente",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // accion_agregar_componente ::= LLAVE_A accion_agregar_componente_p LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_agregar_componente",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // accion_agregar_componente_p ::= opciones_agregar_componente COMA accion_agregar_componente_p 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_agregar_componente_p",39, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // accion_agregar_componente_p ::= opciones_agregar_componente 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_agregar_componente_p",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // opciones_agregar_componente ::= ID PUNTOS IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // opciones_agregar_componente ::= NOMBRE_CAMPO PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // opciones_agregar_componente ::= FORMULARIO PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // opciones_agregar_componente ::= CLASE PUNTOS tipo_clase 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // opciones_agregar_componente ::= TEXTO_VISIBLE ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // opciones_agregar_componente ::= ALINEACION PUNTOS tipo_alineacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // opciones_agregar_componente ::= REQUERIDO PUNTOS required 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // opciones_agregar_componente ::= OPCIONES PUNTOS OPTIONS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // opciones_agregar_componente ::= FILAS PUNTOS NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // opciones_agregar_componente ::= COLUMNAS PUNTOS NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // opciones_agregar_componente ::= URL PUNTOS ALFANUMERICO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_agregar_componente",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // tipo_clase ::= CAMPO_TEXTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_clase",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // tipo_clase ::= AREA_TEXTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_clase",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // tipo_clase ::= CHECKBOX 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_clase",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // tipo_clase ::= RADIO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_clase",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // tipo_clase ::= FICHERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_clase",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // tipo_clase ::= IMAGEN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_clase",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // tipo_clase ::= COMBO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_clase",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // tipo_clase ::= BOTON 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_clase",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // tipo_alineacion ::= CENTRO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_alineacion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // tipo_alineacion ::= IZQUIERDA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_alineacion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // tipo_alineacion ::= DERECHA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_alineacion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // tipo_alineacion ::= JUSTIFICAR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo_alineacion",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // instruccion_eliminacion_componente ::= accion_eliminacion_componente COMA instruccion_eliminacion_componente 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_eliminacion_componente",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // instruccion_eliminacion_componente ::= accion_eliminacion_componente 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_eliminacion_componente",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // accion_eliminacion_componente ::= LLAVE_A accion_eliminacion_componente_p LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_eliminacion_componente",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 105: // accion_eliminacion_componente_p ::= opciones_eliminacion_componente COMA accion_eliminacion_componente_p 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_eliminacion_componente_p",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 106: // accion_eliminacion_componente_p ::= opciones_eliminacion_componente 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_eliminacion_componente_p",40, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 107: // opciones_eliminacion_componente ::= ID PUNTOS IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_eliminacion_componente",50, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 108: // opciones_eliminacion_componente ::= FORMULARIO PUNTOS IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_eliminacion_componente",50, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 109: // instruccion_modificacion_componente ::= accion_modificacion_componente COMA instruccion_modificacion_componente 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_modificacion_componente",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 110: // instruccion_modificacion_componente ::= accion_modificacion_componente 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion_modificacion_componente",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 111: // accion_modificacion_componente ::= LLAVE_A accion_modificacion_componente_p LLAVE_C 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_modificacion_componente",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 112: // accion_modificacion_componente_p ::= opciones_modificacion_componente COMA accion_modificacion_componente_p 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_modificacion_componente_p",41, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 113: // accion_modificacion_componente_p ::= opciones_modificacion_componente 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accion_modificacion_componente_p",41, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 114: // opciones_modificacion_componente ::= FORMULARIO PUNTOS IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_componente",51, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 115: // opciones_modificacion_componente ::= INDICE PUNTOS NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_componente",51, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 116: // opciones_modificacion_componente ::= opciones_agregar_componente 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opciones_modificacion_componente",51, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
